### ISSUE TITLE
Plans to update to EE3?

### ISSUE THREAD

**Issue by carolinecblaker** [davist11/is-ajax#2]
Hi Trevor,

Do you have plans to update this to EE3? I have a site that uses this heavily that's eyeballing the upgrade. 

Thanks!

**Comment by davist11** [comment]
Eventually maybe? Most of my work is Craft work, so it's not a super high priority for me.

**Comment by davist11** [comment]
Actually had a little bit of time to investigate this and just pushed an update to make it EE3 compatible.
